mysql:
  host: localhost
  port: 3306
  username: dialtcp 
  password: Smj4rJac5mf
  dbname: douyin
# redis:
#   host: localhost
#   port: 6379
#   db: 0
jwt:
  # token expire time in minutes
  expire_minutes: 14400
  secret_key: secret
static:
  path: ./static
localip:
  ip: 10.116.89.246
  port: 8080
